[phases.setup]
nixPkgs = ['nodejs_22', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = [
  'pnpm --filter=@scleorg/database db:push',
  'pnpm run build --filter=@scleorg/web'
]

[start]
cmd = 'cd apps/web && pnpm start'
